table D_Products
	lineageTag: 8ed0d57a-2182-4eba-bc8b-3b30b5a114c1

	column Product
		dataType: string
		lineageTag: 5993dbb5-0d2c-4558-aecf-7fd2bec304ac
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 6729564d-b8cb-4393-8858-7a63c8211945
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Cost_per_box
		dataType: double
		lineageTag: d9303546-2b58-4b00-a537-721da2f0c874
		summarizeBy: none
		sourceColumn: Cost_per_box

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PID
		dataType: string
		lineageTag: 0babebbc-e62b-4332-9bd6-c3734dab0c86
		summarizeBy: none
		sourceColumn: PID

		annotation SummarizationSetBy = Automatic

	partition D_Products = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\nagas\Downloads\Choco Company Data.xlsx"), null, true),
				    Products_Sheet = Source{[Item="Products",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product", type text}, {"Category", type text}, {"Cost_per_box", type number}, {"PID", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

